---
  - name: Playbook to search for Windows updates
    hosts: all
    gather_facts: true
    tasks:
      - name: Check version of installed ansible.windows collection
        ansible.builtin.debug:
          msg: "ansible.windows version {{ lookup('community.general.collection_version', 'ansible.windows') }}"
      - name: Search for Windows updates
        ansible.windows.win_updates:
          category_names: "{{ category_names }}"
          server_selection: "{{ server_selection }}"
          state: searched
          log_path: C:\Windows\Temp\ansible_wu.txt
        register: result
      - name: Show result
        ansible.builtin.debug:
          msg: "{{ result }}"